# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-15 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='Car',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='Customer',
            new_name='customer',
        ),
    ]
